### ISSUE TITLE
Unable to change world properties, unknown packet, in AWB 5.0

### ISSUE THREAD

**Issue by TheEeveeLovers** [coremaze/awtools#5]
# The Bug
In ActiveWorlds Browser version **5.0 (Build 1108)**, after loading a world, and at periodic times, an **unknown packet** is received by the universe:
`[2024-06-29T22:40:39Z WARN  universe::universe_server] Received unknown packet opcode 171 from UniverseConnectionID(2). Packet: AWPacket { vars: [AWPacketVar { id: 140, data: Int(1) }, AWPacketVar { id: 97, data: Int(1) }, AWPacketVar { id: 6, data: Int(-2137704234) }], opcode: Unknown(171), header_0: 0, header_1: 2 }`

Also in this version, I cannot edit world properties. The Features panel shows as if I don't have permission, not allowing me to modify any values, despite the fact that I am set as a "caretaker." 
I can edit world properties just fine in **4.3 (build 1054)**
Even in this build of **5.0** I am able to change universe properties just fine, so that's not an issue.
I am still logged in as the caretaking account in question though, as proven by many in-game features and the universe server itself. <br>
**_Could this issue and the unknown packet be related by chance?_** 

# Investigation
So I did some investigating. I would try to figure out the header data and how it relates to known data, and compare it to how it does in the awtools source.
## Assumptions
I made an assumption that the Data for the PacketVar with ID 97 contained the user ID and the one with ID 140 contained the world ID. 
This was because I was logged into a user named Admin, who has a user ID of 1. I was also in a world with an ID of 1.
I ran some tests to make sure these assumptions were true.

## Test 1
For my first test, I would try to see if the PacketVar with ID 97 contained the user ID.
I created a new user, named them Barbara (name has no significance, just example). Her ID was 2.
I joined in the same world and was met on the universe side with a
`[2024-06-29T22:40:58Z WARN  universe::universe_server] Received unknown packet opcode 171 from UniverseConnectionID(2). Packet: AWPacket { vars: [AWPacketVar { id: 140, data: Int(2) }, AWPacketVar { id: 97, data: Int(2) }, AWPacketVar { id: 6, data: Int(-2137704234) }], opcode: Unknown(171), header_0: 0, header_1: 2 }`

### Test Results
As you can see, the data is now 2. This proves that PacketVar ID 97 contains user IDs. However it also disproves the theory that PacketVar ID 140 contains world IDs as it also changed to 2.

## Test 2
For my second test, I would try to see if PacketVar ID 97 or 140's data contained privilege user ID.
No setup was required.
I took the privileges of my Admin account (I forgot to set a privilege password, whoops! At least the universe isn't public yet!)
On the universe side, I was greeted with:
`[2024-06-29T22:44:09Z WARN  universe::universe_server] Received unknown packet opcode 171 from UniverseConnectionID(2). Packet: AWPacket { vars: [AWPacketVar { id: 140, data: Int(1) }, AWPacketVar { id: 97, data: Int(2) }, AWPacketVar { id: 6, data: Int(-2137704234) }], opcode: Unknown(171), header_0: 0, header_1: 2 }`

### Test Results
The PacketVar with ID 140 had its data value change to 1. This proves that the this PacketVar contains privilege user IDs.

## Results
So, the results show:
PacketVar ID 97 - User ID
PacketVar ID 140 - Privilege ID

# Checking source code
Checking the awtools source code,
in [aw_core/src/net/packet_var.rs](../tree/master/aw_core/src/net/packet_var.rs),
ID 97 is LoginID, so that matches
ID 140 is SessionID, however, PrivilegeUserID is ID 100. However this could be a wording issue, much less an actual issue.
####  Maybe some code comments with descriptions on what each var is would help?

ID 6 is VolumeSerial, so it seems to have no significance

# Closing thoughts
## Do you think you could look into this?

**Comment by coremaze** [comment]
This particular issue should be fixed by c23a86d. Packet 171 appears unimportant. I found that privilege login does not work in version 5 but have not investigated any further yet since the primary target is version 4.

**Comment by TheEeveeLovers** [comment]
I will build the new commit and see if the issue subsides. Thank you.

**Comment by TheEeveeLovers** [comment]
I am able to change world and universe properties now. This issue has been fixed. I wonder what packet 171 even was? Of course universes wouldn't be documented to the very packet except in confidential documents (universes aren't publicly documented at all anyways) so we kinda have to figure it out ourselves
